config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'about', to: 'pages#about'
  get 'works', to: 'pages#works'
  get 'contact', to: 'pages#contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_background_image, only: [:home, :about, :contact]
  before_action :set_profile_image, only: :home

  def home
  end

  def about
  end

  def works
  end

  def contact
  end

  private

  def set_background_image
    @background_photo_id = "bdkpyp7oxgemecglhb3i"
  end

  def set_profile_image
    @profile_photo_id = "pp_2"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsProfile</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <!-- <meta name="turbolinks-cache-control" content="no-cache"> -->
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<!-- Fixed Back Button -->
<%= render partial: "./components/fixed_back_button", locals: { path: root_path, label: "home" }%>

<div class="banner" style='background-image: linear-gradient(to right, rgba(255,255,255,0.5), rgba(255,255,255,0.2)), url(<%= cloudinary_url(@background_photo_id, width: 1440, crop:"fill", effect: "grayscale", opacity: 20) %>);'>
  <div class="container about">
    <div class="title pt-5 text-center">
      <h1>about</h1>
    </div>
    <div class="row spacer-above">
    </div>
    <div>
      <h1 class="d-inline">I create </h1><h1 class="elongate-text d-inline">digital solutions</h1><h1 class="d-inline"> for <strong>you</strong></h1>
    </div>
    <div class="row spacer-below">
    </div>
    <div class="row arrow-down">
      <div class="col-12 text-center">
        <h6 class="my-0">Scroll down for more</h6>
        <i class="fas fa-chevron-down"></i>
      </div>
    </div>
  </div>
</div>
<div class="min-vh-100" style="background-color: black; color: white;">
  <div class="container">
    <div class="row">
      <div class="col-12 col-md-3"></div>
      <div class="col-12 col-md-6">
        <h1 class="pt-5 pb-2">About</h1>
        <p style="font-size: 1.25em;">
          Nathaniel is a highly enthusiastic individual that has the apt to learn and create!.
        </p>
        <p>
          Previously a civil and structural engineer trained, Nathaniel takes the dreaded leap of faith into the web developer world. He might be new to the world, but he is willing to learn and always aims to give his best.
        </p>
        <p>
          With 5 years of training as a civil and structural engineer, Nathaniel has done rigorous training to be sharp and meticulous when it comes to details. Equipped with the experience of handling collaborators and clients, he is familiar with handling projects.
        </p>
        <p>
          Nathaniel has a huge interest in giving pleasant visuals. His website design philosophy that he adapts is mobile-first. In order to achieve that, he uses extensive front-end library like Bootstrap.
        </p>
        <p>
          Most of the projects that he has done are based on Ruby on Rails framework. Ruby on Rails are popular with the extensive library and strong community for developing websites, fast deployment of websites, and highly readable.
        </p>
        <p>
          Cooking is one of Nathaniel’s dearest activities! His favorite cuisines are Indonesian and Chinese. Let him know if you are a fellow home-cook and willing to share some amazing recipes!
        </p>
        <div class="py-4"></div>
      </div>
      <div class="col-12 col-md-3"></div>
    </div>
  </div>
</div>

app/views/pages/contact.html.erb
<!-- Fixed Back Button -->
<%= render partial: "./components/fixed_back_button", locals: { path: root_path, label: "home" }%>

<div class="banner" style='background-image: linear-gradient(to right, rgba(255,255,255,0.5), rgba(255,255,255,0.2)), url(<%= cloudinary_url(@background_photo_id, width: 1440, crop:"fill", effect: "grayscale", opacity: 20) %>);'>
  <div class="container">
    <div class="title pt-5 text-center">
      <h1>contact</h1>
    </div>
    <div class="row spacer-above">
    </div>
    <div class="row">
      <div class="col-12 col-md-6 my-3">
        <h1 class="d-inline">Get in </h1><h1 class="d-inline touch"><strong>Touch</strong></h1>
      </div>
      <div class="col-12 col-md-1"></div>
      <div class="col-12 col-md-5">
        <h4>Email me :</h4>
        <p>nathaniel.santosa@gmail.com</p>
        <div style="height: 10%;"></div>
        <h4>Connect with me :</h4>
        <div class="social-media d-flex">
          <%= link_to "https://github.com/nielsantosa", target: "blank" do %>
            <i class="fab fa-github"></i>
          <% end %>
          <%= link_to "https://www.linkedin.com/in/nathaniel-santosa-64a6b6105/", target: "blank" do %>
            <i class="fab fa-linkedin"></i>
          <% end %>
        </div>
      </div>
    </div>
    <div class="row spacer-below">
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner" style='background-image: linear-gradient(to right, rgba(255,255,255,0.5), rgba(255,255,255,0.2)), url(<%= cloudinary_url(@background_photo_id, width: 1440, crop:"fill", effect: "grayscale", opacity: 20) %>);'>
  <div class="container">
      <div class="row spacer-above">
      </div>
      <div class="row">
        <div class="col-12 col-md-8 pb-4">
          <div>
            <h1 class="d-inline">Hello World!</h1>
          </div>
          <div>
            <h1 class="d-inline">I'm </h1><h1 class="elongate-text d-inline"><strong>Nathaniel</strong></h1>
          </div>
        </div>
        <div class="col-12 col-md-4">
          <div class="profile-picture">
            <%= cl_image_tag @profile_photo_id, size: "300x300", crop: "fill" %>
          </div>
        </div>
      </div>
      <div class="row spacer-below">
      </div>
      <div class="row pages">
        <div class="col-12 col-md-4">
          <%= link_to about_path do %>
            <h1>about</h1>
          <% end %>
        </div>
        <div class="col-12 col-md-4">
          <%= link_to works_path do %>
            <h1>works</h1>
          <% end %>
        </div>
        <div class="col-12 col-md-4">
          <%= link_to contact_path do %>
            <h1>contact</h1>
          <% end %>
        </div>
      </div>
  </div>
</div>

app/views/pages/works.html.erb
<!-- Fixed Back Button -->
<%= render partial: "./components/fixed_back_button", locals: { path: root_path, label: "home" }%>

<!-- Progress Bars -->
<div class="progress active fixed-top">
  <div class="progress-bar" role="progressbar"></div>
</div>

<div class="banner">
  <div class="container">
    <div class="title pt-5 text-center">
      <h1>works</h1>
    </div>
    <div class="row">
      <div class="col-12 py-4">
      </div>
      <div class="col-12 mt-5 translate-text">
        <%= link_to works_path(anchor: 'moocoo') do %>
          <h1>moocoo</h1>
          <h5>revolutionizing make-up learning and shopping experience</h5>
        <% end %>
      </div>
      <div class="col-12 mt-5 translate-text">
        <%= link_to works_path(anchor: 'olamoves') do %>
          <h1>olamoves</h1>
          <h5>bringing the movement to you</h5>
        <% end %>
      </div>
      <div class="col-12 mt-5 translate-text">
        <%= link_to works_path(anchor: 'cocktailzilla') do %>
          <h1>cocktailzilla</h1>
          <h5>have fun with our easy-to-use databases for cocktails</h5>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="row my-2">
    <div class="col-12 col-md-3">
    </div>
    <div id="moocoo" class="col-12 col-md-6 border-top">
      <div class="d-flex justify-content-between align-items-center pt-5 pb-3">
        <h1>moocoo</h1>
        <%= link_to "https://moocoo-nielsantosa.herokuapp.com/", target: "blank", class: "link" do %>
          <i class="fas fa-external-link-alt"></i>
        <% end %>
      </div>
      <h2 class="py-3">Overview</h2>
      <p>Moocoo is a web application in passion economy specifically make-up industry where you can enjoy learning and shopping at one go. This is a final project done in 2 weeks during my bootcamp training at Le Wagon Singapore.</p>
      <h2 class="py-3">Product Background</h2>
      <p>Shopping the make-up product on youtube video has always been a hassle. After thousand of clicks and numerous websites to be visited, you just reached the checkout of the products you want. moocoo is here to eliminate all the hassles when learning and shopping, so you can focus more on improving your make-up skills without worrying about the shopping process!</p>
      <h2 class="py-3">Design Background</h2>
      <p>Elegance, modern, and demure is the embodiment of moocoo. moocoo wants its users to fully immersed on the flow rather than worrying about the overly complicated UI/UX. It is heavily targeted on the user journey when buying the products, while keeping the design clean and sleek.</p>
      <div class="row images">
        <% (1..5).to_a.each do |i| %>
        <div class="col-12 col-md-6 py-2">
          <%= cl_image_tag "moo#{i}", alt: "moo#{i}" %>
        </div>
        <% end %>
      </div>
    </div>
    <div class="col-12 col-md-3">
    </div>
  </div>
  <div class="row my-2">
    <div class="col-12 col-md-3">
    </div>
    <div id="olamoves" class="col-12 col-md-6 border-top">
      <div class="d-flex justify-content-between align-items-center pt-5 pb-3">
        <h1>olamoves</h1>
        <%= link_to "https://olamoves-nielsantosa.herokuapp.com/", target: "blank", class: "link" do %>
          <i class="fas fa-external-link-alt"></i>
        <% end %>
      </div>
      <h2 class="py-3">Overview</h2>
      <p>A web application in passion economy especially yoga industry where you can enjoy on-demand yoga tutorials. This is an e-commerce project done in 1-week during my time in Le Wagon bootcamp.</p>
      <h2 class="py-3">Product Background</h2>
      <p>LOlamoves is a by-product of on-demand yoga videos. It is targeted to the yoga community that is impacted by Covid-19 - where they cannot attend the yoga classes physically. Bringing the movements to the users, olamoves can be accessed anytime, anywhere.</p>
      <h2 class="py-3">Design Background</h2>
      <p>Calm, energizing, and fresh - those adjectives are the foundation of olamoves design. The aesthetic is meant to enhance the users physical and spiritual journey with olamoves.</p>
      <div class="row images">
        <% (1..4).to_a.each do |i| %>
        <div class="col-12 py-2">
          <%= cl_image_tag "ola#{i}", alt: "ola#{i}" %>
        </div>
        <% end %>
      </div>
    </div>
    <div class="col-12 col-md-3">
    </div>
  </div>
  <div class="row my-2">
    <div class="col-12 col-md-3">
    </div>
    <div id="cocktailzilla" class="col-12 col-md-6 border-top">
      <div class="d-flex justify-content-between align-items-center pt-5 pb-3">
        <h1>cocktailzilla</h1>
        <%= link_to "https://mister-cocktail-nielsantosa.herokuapp.com/", target: "blank", class: "link" do %>
          <i class="fas fa-external-link-alt"></i>
        <% end %>
      </div>
      <p>Cocktailzilla is an assignment from Le Wagon Singapore for creating a cocktail databases using Ruby on Rails framework. Users can find, add, or edit the cocktails they found on the database!</p>
      <h2 class="py-3">Design Background</h2>
      <p>Cocktailzilla believes in being minimalist and simple. It is modest because it is just a databases. The design is targeted to give the users the ease of finding and viewing. It does not want to overcomplicate a simple database.</p>
      <div class="row images">
        <div class="col-12 py-2">
          <%= cl_image_tag "cock1", alt: "cock1" %>
        </div>
      </div>
    </div>
    <div class="col-12 col-md-3">
    </div>
  </div>
  <div class="row py-3">
  </div>
</div>